data =               {'1': 'steal',
                      '2': 'money',
                      '3':'heist',
                      '4':'robbery',
                      '5':'thief',
                      '6':'store money',
                      '7':'cyber banking',
                      '8':'shoplift',
                      '9':'bank vault',
                      '10':'theft',
                      '11':'break',
                      '12':'alarm',
                      '13':'money chest',
                      '14':'rash',
                      '15':'trojan',
                      '16':'virus',
                      '17':'attack',
                      '18':'malware',
                      '19':'trick',
                      '20':'fool',
                      '21':'dark web',
                      '22':'tor',
                      '23':'hack',
                      '24':'theft',
                      '25':'steal',
                      '26':'embezzle',
                      '27':'crime',
                      '28':'fraud',
                      '29':'offshore',
                      '30':'fraudulent',
                      '31':'money laundering',
                      '32':'corruption',
                      '33':'heist',
                      '34':'lie',
                      '35':'lying',
                      '36':'access control',
                      '37':'anti-virus',
                      '38':'anti-malware',
                      '39':'antivirus',
                      '40':'apt',
                      '41':'advanced persistent threat',
                      '42':'asset',
                      '43':'authentication',
                      '44':'authorization',
                      '45':'backing up',
                      '46':'blacklist',
                      '47':'botnet',
                      '48':'bug',
                      '48':'clickjacking',
                      '49':'cnd',
                      '50':'computer network defense',
                      '51':'cyberattack',
                      '52':'cyber ecosystem',
                      '53':'cyberespionage',
                      '54':'data breach',
                      '55':'data theft',
                      '56':'ddos attack',
                      '57':'distributed denial of service',
                      '58':'decrypt',
                      '59':'digital certificate',
                      '60':'digital forensics',
                      '61':'dlp',
                      '62':'dos',
                      '63':'denial of service',
                      '64':'drive by download',
                      '65':'eavesdropping',
                      '66':'encode',
                      '67':'firewall',
                      '68':'hacker',
                      '69':'hacktivism',
                      '70':'honeypot',
                      '71':'identity cloning',
                      '72':'identity fraud',
                      '73':'ids',
                      '74':'intrusion detection system',
                      '75':'insider threat',
                      '76':'jboh',
                      '77':'javascript binding over http',
                      '78':'Keylogger',
                      '79':'link jacking',
                      '80':'malware',
                      '81':'outsider threat',
                      '82':'outsourcing',
                      '83':'packet sniffing',
                      '84':'payment card skimmers',
                      '85':'phishing',
                      '86':'ransomware',
                      '87':'sniffing',
                      '88':'spear phishing',
                      '89':'spoof',
                      '90':'spoofing',
                      '91':'spyware',
                      '92':'unauthorized access',
                      '93':'virus',
                      '94':'vishing',
                      '95':'worm',
                      '96':'zombie',
                      '97':'crash',
                      '98':'attack',
                      '99':'trick',
                      '100':'fool',
                      '101':'dark web',
                      '102':'hack',
                      '103':'theft',
                      '104':'steal',
                      '105':'embezzle',
                      '106':'crime',
                      '107':'fraud',
                      '108':'offshore',
                      '109':'Fraudulent',
                      '110':'moneylaundering',
                      '111':'corruption',
                      '112':'heists',
                      '113':'vpn',
                      '114':'virtual private network'}
